sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker

before_install:
  - chmod +x mvnw
  - docker-compose -t docker-java-travis build

script:
  - docker run docker-java-travis mvn test